language: php
sudo: false

php:
  - 7.3
  - 7.4
  - 8.0

before_install:
  - echo "Disable xdebug" && phpenv config-rm xdebug.ini

install:
  - composer update --prefer-dist

script:
  - ./vendor/bin/phpunit
